#!/bin/bash

export PATH="${PATH}:${HOME}/.local/bin/"

swww init

if [ -e "${HOME}/.cache/wal/colors" ]; then
    wal -R --cols16

    echo "Cached colors exist. Using existing colors."
else
    DIR=$HOME/Wallpapers
    PICS=($(ls ${DIR}))

    RANDOMPICS=${PICS[$RANDOM % ${#PICS[@]}]}

    swww img ${DIR}/${RANDOMPICS} --transition-type wipe --transition-fps 60 --transition-duration 2 --transition-angle 30 --transition-step 90

    wal -i ${DIR}/${RANDOMPICS} --cols16

    echo "Successfully set a new wallpaper and generated colors from it."
fi

pywalfox update
# pywal-discord -t default
# wal-telegram --wal

. $HOME/.config/mako/update-colors.sh
. $HOME/.config/spicetify/Themes/Pywal/update-colors.sh
. $HOME/.config/cava/scripts/update-colors.sh
