#!/bin/bash

export PATH="${PATH}:${HOME}/.local/bin/"

dir="$HOME/.config/rofi/launchers/type-1"
theme='style-1'
ACTIVE_WALLPAPER_PATH="$HOME/.cache/active-wallpaper-path"

wallpapers=$HOME/Pictures/Wallpapers
image="$(ls $wallpapers | rofi -dmenu -i -p "Select wallpaper" -theme ${dir}/${theme}.rasi)"
wallpaper=$wallpapers/$image

if [[ -d $wallpapers/$image ]]; then
    echo "$wallpapers/$image is a directory"
    wallpaper_temp="$image"
    sleep2
    wallpaper_location="$(ls $wallpapers/$image | wofi -n --show dmenu -k "/dev/null")"
elif [[ -f $wallpapers/$image ]]; then
    echo "$wallpapers/$image is a file"
else
    echo "$wallpapers/$image is not valid"
    exit 1
fi

if [[ $(pidof swaybg) ]]; then
    pkill swaybg
fi

sleep 1

swaybg -i $wallpapers/$image
wal -i $wallpapers/$image --cols16
pywalfox update

echo "$wallpapers/$image" >"$ACTIVE_WALLPAPER_PATH"
. $HOME/.config/mako/update-colors.sh
. $HOME/.config/mako/update-theme.sh
. $HOME/.config/spicetify/Themes/Pywal/update-colors.sh
. $HOME/.config/cava/scripts/update-colors.sh
