#!/bin/bash

export PATH="${PATH}:${HOME}/.local/bin/"

dir="$HOME/.config/rofi/launchers/type-1"
theme='style-1'

wallpapers=$HOME/Wallpapers
image="$(ls $wallpapers | rofi -dmenu -i -p "Select wallpaper" -theme ${dir}/${theme}.rasi)"
wallpaper=$wallpapers/$image

if [[ -d $wallpapers/$image ]]; then
    echo "$wallpapers/$image is a directory"
    wallpaper_temp="$image"
    sleep2
    wallpaper_location="$(ls $wallpapers/$image | wofi -n --show dmenu -k "/dev/null")"
elif [[ -f $wallpapers/$image ]]; then
    echo "$wallpapers/$image is a file"
else
    echo "$wallpapers/$image is not valid"
    exit 1
fi

swww img $wallpaper --transition-type wipe --transition-fps 60 --transition-duration 0.5 --transition-angle 30 --transition-step 90
sleep 0.5

wal -i $wallpaper --cols16
pywalfox update
pywal-discord -t default
wal-telegram --wal

. $HOME/.config/mako/update-colors.sh
. $HOME/.config/mako/update-theme.sh
. $HOME/.config/spicetify/Themes/Pywal/update-colors.sh
. $HOME/.config/cava/scripts/update-colors.sh
